services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=mechi
      - POSTGRES_PASSWORD=backend_to_the_future
      - POSTGRES_DB=pagina
    ports:
      - 5432:5432
    volumes:
      - ./psql_data:/var/lib/postgresql/data
